aliases: []
creation_timestamp: 1783748172166
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1783748172166
metrics: null
model_id: m-e446ae91d9894716b1780a2edb38645c
name: XGboost
params: null
run_id: ''
run_link: ''
source: file:///home/student/Documents/customer_churn_prediction_with_deployment/mlruns/673747014708825872/models/m-e446ae91d9894716b1780a2edb38645c/artifacts
status: READY
status_message: null
storage_location: file:///home/student/Documents/customer_churn_prediction_with_deployment/mlruns/673747014708825872/models/m-e446ae91d9894716b1780a2edb38645c/artifacts
user_id: null
version: 1
